-- Optional one-time seed: run this in the Supabase SQL editor (after schema.sql) to bulk-load
-- the guest list. Side / RSVP / meal choice are left unset — edit them later on guests.html.
insert into public.guests (name) values
  ('Gihan'),
  ('Samir Wahba'),
  ('Mario Samir'),
  ('George Samir'),
  ('Mario Samir'),
  ('Amy Samir'),
  ('Injy'),
  ('Marco'),
  ('Lolly(alby)'),
  ('Mirna'),
  ('Bishoy'),
  ('Hanan'),
  ('Maged'),
  ('Tony'),
  ('Eva'),
  ('Bavely'),
  ('Kirolos'),
  ('Philo'),
  ('Mina'),
  ('Nader'),
  ('Viola'),
  ('Mourad'),
  ('Maichel'),
  ('Samia'),
  ('Sanaa'),
  ('Gamal'),
  ('Mema'),
  ('Ahdy'),
  ('Martha'),
  ('Maged'),
  ('Medhat'),
  ('Sandy'),
  ('Magdy'),
  ('Mervat'),
  ('Goz Mervat'),
  ('Peter Mervat'),
  ('Soaad'),
  ('Boussy'),
  ('Beshoy Boussy'),
  ('Peter Boussy'),
  ('Magdy'),
  ('Vevian'),
  ('Mamdouh'),
  ('Eman'),
  ('Mamdouh'),
  ('Mamdouh'),
  ('George'),
  ('Amal'),
  ('George'),
  ('George'),
  ('Nesiem'),
  ('Nesim'),
  ('Romany'),
  ('Romany'),
  ('Romany'),
  ('Jackline'),
  ('Magdy'),
  ('Jackline'),
  ('Jackline'),
  ('Jackline'),
  ('Maichel'),
  ('Maichel'),
  ('John'),
  ('John'),
  ('Monica'),
  ('Monica'),
  ('Manal'),
  ('Gergis'),
  ('Gergigs'),
  ('Gergis'),
  ('Monica'),
  ('Monica'),
  ('Mina'),
  ('Mina'),
  ('Felopater'),
  ('Abanoub'),
  ('Abanoub'),
  ('Fady'),
  ('Macarina'),
  ('Bishoy'),
  ('Lourine'),
  ('Hosam'),
  ('Randa'),
  ('Mario'),
  ('Fady hosny'),
  ('Bishoy Raafat'),
  ('Mina esam'),
  ('mina esam'),
  ('Mamet abnoub'),
  ('Akho abanoub'),
  ('Okht abanoub'),
  ('Peter azer'),
  ('Mariam'),
  ('Mariam Sameh'),
  ('Fady'),
  ('Mirna wagih'),
  ('David'),
  ('Youstina metry'),
  ('Bahgat'),
  ('Rawan'),
  ('Amr hany'),
  ('Carole'),
  ('Baher'),
  ('Farah'),
  ('Injy'),
  ('Okasha'),
  ('Sara Abbas'),
  ('Mamdouh'),
  ('Buu'),
  ('Abdelouhab'),
  ('Abdelouhab'),
  ('Abdelouhab'),
  ('Mina samir'),
  ('Mina samir'),
  ('Mina adel'),
  ('Nabil Boushra'),
  ('Ibrahim'),
  ('Fady'),
  ('Ayad'),
  ('Olivia'),
  ('Kero'),
  ('Iriny'),
  ('Dodo'),
  ('Elarya'),
  ('Jano'),
  ('Jerry'),
  ('Jack'),
  ('Yara'),
  ('Jana'),
  ('Rahma'),
  ('Moamen'),
  ('Yousry'),
  ('Ali'),
  ('Bella'),
  ('Mohra'),
  ('Sandy'),
  ('Jessy'),
  ('Yara'),
  ('Beshir'),
  ('Beshir'),
  ('Salma'),
  ('Shanwany'),
  ('Sabry'),
  ('Mina mourad'),
  ('Merolla'),
  ('Youhanna'),
  ('Arian'),
  ('Marat arian'),
  ('Shenoda'),
  ('Roula'),
  ('Wezza'),
  ('Marat wezza'),
  ('Bashnouna'),
  ('Mrato'),
  ('Amir'),
  ('Taher'),
  ('Marato'),
  ('Khaled'),
  ('Ahmed Hamada'),
  ('John NI'),
  ('John'),
  ('Marina'),
  ('Eva'),
  ('Amir'),
  ('Maria'),
  ('Lavy'),
  ('Mariaa NI'),
  ('Mina emil'),
  ('Sandy'),
  ('Youssef'),
  ('Virginia'),
  ('Paula Nabil'),
  ('David Pierre tanya abtda2y'),
  ('Lucia Ayman'),
  ('Sherry'),
  ('Mirette'),
  ('Monica Essam'),
  ('Muller'),
  ('Mirette 3erian'),
  ('Vero'),
  ('Youstina'),
  ('Goz youstina'),
  ('Abo 3erian'),
  ('Om 3erian'),
  ('Mariam'),
  ('Fady'),
  ('Tony'),
  ('Fady Fayez'),
  ('Fady Fayez'),
  ('Tony'),
  ('Tony'),
  ('Pierre ashraf'),
  ('Mamet Bella'),
  ('Fadaly'),
  ('Mona Tls'),
  ('Goz Mona tls'),
  ('Abeet tls'),
  ('Dina'),
  ('Besho akho Dina'),
  ('Baba Dina'),
  ('Mamet Dina'),
  ('Remon Gamal'),
  ('Marina merat Remon'),
  ('Ramy Gamal'),
  ('Romany Gamal'),
  ('Hany Maher'),
  ('Mervat merat Hany'),
  ('Sondos Ni'),
  ('Mabrouk Ni'),
  ('Lubna Ni'),
  ('Merna Belal NI'),
  ('Zeyad NI'),
  ('Khafagy N'),
  ('Fady NI'),
  ('Fadi Magnati'),
  ('Mamet Mema'),
  ('Ebrahim Mario'),
  ('Gendy Mario'),
  ('Sokar'),
  ('Merna Eha'),
  ('Maria'),
  ('Katkouta'),
  ('Nardeen Mario'),
  ('Passant Mario'),
  ('Lydia Mario'),
  ('Jolie Mario'),
  ('Pavly Mario'),
  ('Jolie Amy'),
  ('Jounir Amy'),
  ('Farida Amy'),
  ('Tarek Tls'),
  ('Zeinab merat Tarek'),
  ('Amany Gihan'),
  ('Rafaat Gihan'),
  ('Abanoun Gihan'),
  ('Youstina Gihan'),
  ('Ashraf Gihan'),
  ('Oussama Kadry'),
  ('Merat Oussama Kadry'),
  ('Ehab Kadry'),
  ('Merat Ehab Kadry'),
  ('Remon Kadry'),
  ('Merat Remon Kadry'),
  ('El haj Mohamed'),
  ('Merat el haj Mohamed'),
  ('Marwan ebn el Haji Moahemd'),
  ('Manal Kadry'),
  ('Goz Manal Kadry'),
  ('Ebn Manal Kadry'),
  ('Ebn Manal Kadry'),
  ('Ramy Kamal'),
  ('Merat Ramy Kamal'),
  ('Misho Kamal'),
  ('Merat Misho Kamal'),
  ('Remon Kamal'),
  ('Rania Kamal'),
  ('Goz Rania Kamal'),
  ('Marina Magdy Wahba'),
  ('Goz Marina Magdy'),
  ('Fadi Magdy wahba'),
  ('Merat Magdy wahba'),
  ('Beshoy Magdy wahba'),
  ('Merat Beahoy Wahba'),
  ('Mamet Salma Gam3a'),
  ('Hannah okht Salma Gam3a'),
  ('Goz Yara Gam3a'),
  ('Ashraf Kamal Shehata'),
  ('Salwa Kamal Shehata'),
  ('Samir Kamal Sheahata'),
  ('Dalia Kamal Shehata'),
  ('Alfred Hadana'),
  ('Andrew Nassief Hadana');
